# Generated by Django 6.0.3 on 2026-04-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0003_examresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integritylog',
            old_name='student',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='integritylog',
            name='event_type',
            field=models.CharField(choices=[('tab_switch', 'Tab Switch'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt'), ('right_click', 'Right Click'), ('refresh', 'Refresh'), ('devtools', 'DevTools')], max_length=50),
        ),
    ]
