# Generated by Django 6.0.3 on 2026-04-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0004_rename_student_integritylog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='integrity_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='examresult',
            name='risk_level',
            field=models.CharField(default='LOW', max_length=20),
        ),
    ]
