# Generated by Django 6.0.3 on 2026-04-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0006_subjectassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examattempt',
            old_name='submitted_at',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='examattempt',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
