# Generated by Django 6.0.3 on 2026-04-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0008_remove_studentanswer_attempt_studentanswer_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10),
        ),
    ]
