# Generated by Django 6.0.3 on 2026-04-06 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0012_subject_code_subject_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam_system.exam'),
        ),
    ]
