# Generated by Django 6.0.3 on 2026-04-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0014_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='integritylog',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
