# Generated by Django 6.0.3 on 2026-04-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0015_integritylog_is_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
    ]
