# Generated by Django 6.0.3 on 2026-04-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0016_remove_question_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
