# Generated by Django 6.0.3 on 2026-04-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0017_exam_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
