# Generated by Django 6.0.3 on 2026-04-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0018_examattempt_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
