# Generated by Django 6.0.3 on 2026-04-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0020_exam_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
