# Generated by Django 6.0.3 on 2026-05-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0021_exam_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='integritylog',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='integritylog',
            name='event_type',
            field=models.CharField(choices=[('tab_switch', 'Tab Switch'), ('fullscreen_exit', 'Fullscreen Exit'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt'), ('right_click', 'Right Click'), ('refresh', 'Refresh'), ('devtools', 'DevTools')], max_length=50),
        ),
    ]
