# Generated by Django 6.0.3 on 2026-05-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0022_integritylog_severity_alter_integritylog_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integritylog',
            name='is_reviewed',
        ),
    ]
