# Generated by Django 6.0.3 on 2026-05-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0023_remove_integritylog_is_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integritylog',
            name='severity',
        ),
        migrations.AddField(
            model_name='integritylog',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='integritylog',
            name='event_type',
            field=models.CharField(choices=[('tab_switch', 'Tab Switch'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt'), ('right_click', 'Right Click'), ('refresh', 'Refresh'), ('devtools', 'DevTools')], max_length=50),
        ),
    ]
