# Generated by Django 6.0.3 on 2026-05-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0024_remove_integritylog_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='Earliest date & time students can start the exam.', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='available_until',
            field=models.DateTimeField(blank=True, help_text='Latest date & time students can start the exam.', null=True),
        ),
    ]
