# Generated by Django 6.0.3 on 2026-05-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0025_exam_available_from_exam_available_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration_enabled',
            field=models.BooleanField(default=True, help_text='When disabled, students have unlimited time.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Minutes allowed; ignored when duration_enabled is False.', null=True),
        ),
    ]
