# Generated by Django 6.0.3 on 2026-05-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0026_exam_duration_enabled_alter_exam_duration'),
    ]

    operations = [
    ]
