# Generated by Django 6.0.3 on 2026-05-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0028_int_log_review_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Instructors can manually open/close an exam regardless of the time window.'),
        ),
    ]
