# Generated by Django 6.0.3 on 2026-06-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0029_exam_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
