# Generated by Django 6.0.3 on 2026-07-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0032_populate_percentage_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
