# Generated by Django 6.0.3 on 2026-07-14 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0033_subject_archived_at_subject_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total_questions',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
